/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as EffectRouteImport } from './routes/effect'
import { Route as LoadedRouteImport } from './routes/loaded'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SeriesPersonIdRouteImport } from './routes/series.$personId'
import { Route as VisitIndexRouteImport } from './routes/visit.index'
import { Route as VisitVisitIdRouteImport } from './routes/visit.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectRoute = EffectRouteImport.update({
  id: '/effect',
  path: '/effect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadedRoute = LoadedRouteImport.update({
  id: '/loaded',
  path: '/loaded',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeriesRoute,
} as any)
const SeriesPersonIdRoute = SeriesPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => SeriesRoute,
} as any)
const VisitIndexRoute = VisitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisitRoute,
} as any)
const VisitVisitIdRoute = VisitVisitIdRouteImport.update({
  id: '/$visitId',
  path: '/$visitId',
  getParentRoute: () => VisitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/effect': typeof EffectRoute
  '/loaded': typeof LoadedRoute
  '/panel': typeof PanelRoute
  '/protocol': typeof ProtocolRoute
  '/series': typeof SeriesRouteWithChildren
  '/visit': typeof VisitRouteWithChildren
  '/series/$personId': typeof SeriesPersonIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/series/': typeof SeriesIndexRoute
  '/visit/': typeof VisitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/effect': typeof EffectRoute
  '/loaded': typeof LoadedRoute
  '/panel': typeof PanelRoute
  '/protocol': typeof ProtocolRoute
  '/series/$personId': typeof SeriesPersonIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/series': typeof SeriesIndexRoute
  '/visit': typeof VisitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/effect': typeof EffectRoute
  '/loaded': typeof LoadedRoute
  '/panel': typeof PanelRoute
  '/protocol': typeof ProtocolRoute
  '/series': typeof SeriesRouteWithChildren
  '/visit': typeof VisitRouteWithChildren
  '/series/$personId': typeof SeriesPersonIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/series/': typeof SeriesIndexRoute
  '/visit/': typeof VisitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compute'
    | '/effect'
    | '/loaded'
    | '/panel'
    | '/protocol'
    | '/series'
    | '/visit'
    | '/series/$personId'
    | '/visit/$visitId'
    | '/series/'
    | '/visit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compute'
    | '/effect'
    | '/loaded'
    | '/panel'
    | '/protocol'
    | '/series/$personId'
    | '/visit/$visitId'
    | '/series'
    | '/visit'
  id:
    | '__root__'
    | '/'
    | '/compute'
    | '/effect'
    | '/loaded'
    | '/panel'
    | '/protocol'
    | '/series'
    | '/visit'
    | '/series/$personId'
    | '/visit/$visitId'
    | '/series/'
    | '/visit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeRoute: typeof ComputeRoute
  EffectRoute: typeof EffectRoute
  LoadedRoute: typeof LoadedRoute
  PanelRoute: typeof PanelRoute
  ProtocolRoute: typeof ProtocolRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  VisitRoute: typeof VisitRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effect': {
      id: '/effect'
      path: '/effect'
      fullPath: '/effect'
      preLoaderRoute: typeof EffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loaded': {
      id: '/loaded'
      path: '/loaded'
      fullPath: '/loaded'
      preLoaderRoute: typeof LoadedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/series/$personId': {
      id: '/series/$personId'
      path: '/$personId'
      fullPath: '/series/$personId'
      preLoaderRoute: typeof SeriesPersonIdRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/visit/': {
      id: '/visit/'
      path: '/'
      fullPath: '/visit/'
      preLoaderRoute: typeof VisitIndexRouteImport
      parentRoute: typeof VisitRoute
    }
    '/visit/$visitId': {
      id: '/visit/$visitId'
      path: '/$visitId'
      fullPath: '/visit/$visitId'
      preLoaderRoute: typeof VisitVisitIdRouteImport
      parentRoute: typeof VisitRoute
    }
  }
}

interface SeriesRouteChildren {
  SeriesPersonIdRoute: typeof SeriesPersonIdRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesPersonIdRoute: SeriesPersonIdRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

interface VisitRouteChildren {
  VisitVisitIdRoute: typeof VisitVisitIdRoute
  VisitIndexRoute: typeof VisitIndexRoute
}

const VisitRouteChildren: VisitRouteChildren = {
  VisitVisitIdRoute: VisitVisitIdRoute,
  VisitIndexRoute: VisitIndexRoute,
}

const VisitRouteWithChildren = VisitRoute._addFileChildren(VisitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeRoute: ComputeRoute,
  EffectRoute: EffectRoute,
  LoadedRoute: LoadedRoute,
  PanelRoute: PanelRoute,
  ProtocolRoute: ProtocolRoute,
  SeriesRoute: SeriesRouteWithChildren,
  VisitRoute: VisitRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
